
spring:
  application:
    name: "configserver"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/WildlifeCoder/bank-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "file:C:/Users/miguel.a.coy.triana/Documents/microservices/config"
          #search-locations: "classpath:/config

server:
  port: 8071


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
